---
- hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: Create staging folder
      file: 
        path: files/staging/{{ inventory_hostname }}
        state: directory
        mode: 0755
    - name: Create completion folder
      file:
        path: files/complete
        state: directory
        mode: 0755
  tags: build

- hosts: all
  gather_facts: false
  connection: local
  roles:
    - header
    - vrf
    - body
    - interface
    - ospf
    - footer
  tags: build

- name: Create configuration files
  hosts: all
  gather_facts: no
  connection: local
  tasks:
   - name: Assemble final configuration files
     assemble:  
       src: "files/staging/{{ inventory_hostname }}/" 
       dest: "files/complete/{{ inventory_hostname }}_final.cfg"
  tags: build

#- name: Push config to production
#  hosts: all
#  gather_facts: false
#  connection: local
#  become: true
#  tasks: 
#    - name: NAPALM replace config
#      napalm_install_config:
#        config_file: ./files/complete/{{ inventory_hostname }}_final.cfg
#        commit_changes: false
#        replace_config: true
#  tags: push

- name: Push config via NAPALM
  hosts: all
  gather_facts: false
  connection: local
  become: true
  tasks:
    - napalm_install_config:
        config_file: "./files/complete/{{ inventory_hostname }}_final.cfg"
        commit_changes: true
        replace_config: true
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        dev_os: "{{ ansible_network_os }}"
        password: "{{ ansible_ssh_pass }}"
        timeout: 20
        get_diffs: false
      register: result

