---
- name: Executing RP change on all nodes
  hosts: all
  gather_facts: no
  connection: local
  tasks:
    - ios_config:
        lines:
          - no ip pim rp-address 150.1.3.3 10
          - ip pim rp-address 150.1.2.2 10
        save_when: modified
      register: my_ios_change
