---
- hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: Create staging folder
      file: 
        path: files/staging/{{ inventory_hostname }}
        state: directory
        mode: 0755

- hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: Create completion folder
      file:
        path: files/complete
        state: directory
        mode: 0755

- hosts: all
  gather_facts: false
  connection: local
  roles:
    - header
    - vrf
    - body
    - interface
    - ospf
    - footer

- name: Create configuration files
  hosts: all
  gather_facts: no
  connection: local
  tasks:
   - name: Assemble final configuration files
     assemble:  
       src: "files/staging/{{ inventory_hostname }}/" 
       dest: "files/complete/{{ inventory_hostname }}_final.cfg"

- name: Push config to production
  hosts: all
  gather_facts: false
  connection: local
  tasks: 
    - name: Loading config to node
      ios_config:
        src: "./files/complete/{{ inventory_hostname }}_final.cfg"
    - name: Saving config to node
      ios_config:
        save_when: modified
