---
ansible_connection: network_cli
ansible_become: yes
ansible_become_method: enable

domain_name: "test.com"

users:
  - username: cisco
    password: cisco
  - username: test
    password: test

secret: cisco

ntp_servers:
  - 10.1.1.100

rp_address: 150.1.2.2
