---
my_asn: 2

interfaces:
  Loopback0:
    ip: 150.1.2.2/32
    description: mgmt_loopback
    enabled: true
  GigabitEthernet0/0:
    ip: 192.168.137.212/24
    vrf: MGMT
    description: oob
    enabled: true
  GigabitEthernet0/1:
    ip: 10.0.23.2/24
    description: link_to_r03
    enabled: true
  GigabitEthernet0/2:
    ip: 10.0.25.2/24
    description: link_to_r05
    enabled: true
  GigabitEthernet0/3:
    ip: 10.0.12.2/24
    description: link_to_r01
    enabled: true

bgp:
  - peer: 10.0.12.1
    asn: 1
  - peer: 10.0.23.3
    asn: 3
  - peer: 10.0.25.5
    asn: 5
