---
my_asn: 3

interfaces:
  Loopback0:
    ip: 150.1.3.3/32
    description: mgmt_loopback
    enabled: true
  GigabitEthernet0/0:
    ip: 192.168.137.213/24
    vrf: MGMT
    description: oob
    enabled: true
  GigabitEthernet0/1:
    ip: 10.0.23.3/24
    description: link_to_r02
    enabled: true
  GigabitEthernet0/2:
    ip: 10.0.34.3/24
    description: link_to_r04
    enabled: true

bgp:
  - peer: 10.0.23.2
    asn: 2
  - peer: 10.0.34.4
    asn: 4
