---
- name: Backup Config
  hosts: all
  gather_facts: no
  connection: local  
  tasks:
    - name: Gathering configuration
      ios_config:
        backup: yes
        provider:
          authorize: yes 
      register: switch_backups

 
- name: Add R1 interface label
  hosts: 10.0.0.1
  gather_facts: no
  connection: local
  tasks:
  - ios_config:
      provider:
        authorize: yes
      lines:
        - description MY_LABEL_GOES_HERE
      parents: interface GigabitEthernet1.12
