---
all:
  children:
    my_cml:
      hosts:
        R01:
          ansible_host: 10.1.1.1
          ansible_network_os: ios
        R02:
          ansible_host: 10.1.1.2
          ansible_network_os: ios
        R03:
          ansible_host: 10.1.1.3
          ansible_network_os: ios
        R04:
          ansible_host: 10.1.1.4
          ansible_network_os: ios
        R05:
          ansible_host: 10.1.1.5
          ansible_network_os: ios
        R06:
          ansible_host: 10.1.1.6
          ansible_network_os: ios
        R10:
          ansible_host: 10.1.1.10
          ansible_network_os: ios
