---
all:
  children:
    my_cml:
      children:
        nxos_devices:
          hosts:
            SW01:
              ansible_host: 192.168.137.241
              ansible_network_os: nxos
        ios_devices:
          hosts:
            R01:
              ansible_host: 192.168.137.242
              ansible_network_os: ios
            R02:
              ansible_host: 192.168.137.243
              ansible_network_os: ios
