---
- name: Backup Config
  hosts: all
  gather_facts: no
  connection: local  
  tasks:
    - name: Gathering configuration
      eos_config:
        backup: yes
        provider:
          authorize: yes 
      register: switch_backups

    - name: Create vlan 10
      eos_vlan:
        authorize: yes
        vlan_id: 10
        name: server_vlan_10
        state: present

    - name: Add interface to vlan 10
      eos_vlan:
        authorize: yes
        vlan_id: 10
        interfaces:
           - Ethernet1
