---
my_asn: 35

interfaces:
  Loopback0:
    ip: 150.1.3.3/32
    description: mgmt_loopback
    ospf:
      process: 1
      area: 0
    enabled: true
  GigabitEthernet1.23:
    ip: 155.1.23.3/24
    description: link_to_r2
    encapsulation: 23
#    ospf:
#      process: 1
#      area: 0
#      network_type: "point-to-point"
#      password: myospfpassword
    pim: true
    enabled: true
  GigabitEthernet1.34:
    ip: 155.1.34.3/24
    description: link_to_r4
    encapsulation: 34
#    ospf:
#      process: 1
#      area: 0
#      network_type: "point-to-point"
#      password: myospfpassword
    pim: true
    enabled: true
  GigabitEthernet1.35:
    ip: 155.1.35.3/24
    description: link_to_r5
    encapsulation: 35
    ospf:
      process: 1
      area: 0
      network_type: "point-to-point"
      password: myospfpassword
    pim: true
    enabled: true

bgp:
  - peer: 150.1.5.5
    asn: 35
    update_source: Loopback0
    next_hop_self: True
  - peer: 155.1.23.2
    asn: 12
  - peer: 155.1.34.4
    asn: 4
