---
my_asn: 4

interfaces:
  Loopback0:
    ip: 150.1.4.4/32
    description: mgmt_loopback
    ospf:
      process: 1
      area: 0
    enabled: true
  GigabitEthernet1.14:
    ip: 155.1.14.4/24
    description: link_to_r1
    encapsulation: 14
#    ospf:
#      process: 1
#      area: 0
#      network_type: "point-to-point"
#      password: myospfpassword
    pim: true
    enabled: true
  GigabitEthernet1.24:
    ip: 155.1.24.4/24
    description: link_to_r2
    encapsulation: 24
#    ospf:
#      process: 1
#      area: 0
#      network_type: "point-to-point"
#      password: myospfpassword
    pim: true
    enabled: true
  GigabitEthernet1.34:
    ip: 155.1.34.4/24
    description: link_to_r3
    encapsulation: 34
#    ospf:
#      process: 1
#      area: 0
#      network_type: "point-to-point"
#      password: myospfpassword
    pim: true
    enabled: true
  GigabitEthernet1.45:
    ip: 155.1.45.4/24
    description: link_to_r5
    encapsulation: 45
#    ospf:
#      process: 1
#      area: 0
#      network_type: "point-to-point"
#      password: myospfpassword
    pim: true
    enabled: true

bgp:
  - peer: 155.1.24.2
    asn: 12
  - peer: 155.1.34.3
    asn: 35
  - peer: 155.1.14.1
    asn: 12
  - peer: 155.1.45.5
    asn: 35
