---
- hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: Create staging folder
      file: 
        path: files/staging/{{ inventory_hostname }}
        state: directory
        mode: 0755

- hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: Create completion folder
      file:
        path: files/complete
        state: directory
        mode: 0755

- hosts: leafs
  gather_facts: false
  connection: local
  roles:
    - bgp

- name: Create configuration files
  hosts: all
  gather_facts: no
  connection: local
  tasks:
   - name: Assemble final configuration files
     assemble:  
       src: "files/staging/{{ inventory_hostname }}/" 
       dest: "files/complete/{{ inventory_hostname }}_final.cfg"
