---
all:
  children:
    multicast:
      hosts:
        R01:
          ansible_host: 192.168.137.211
          ansible_network_os: ios
        R02:
          ansible_host: 192.168.137.212
          ansible_network_os: ios
        R03:
          ansible_host: 192.168.137.213
          ansible_network_os: ios
        R04:
          ansible_host: 192.168.137.214
          ansible_network_os: ios
        R05:
          ansible_host: 192.168.137.215
          ansible_network_os: ios
