---
- name: Add R4 static route
  hosts: 10.0.0.4
  gather_facts: no
  connection: local
  tasks:
  - ios_static_route:
      provider:
        authorize: yes
      prefix: 99.99.99.99
      mask: 255.255.255.255
      next_hop: null0
