---
my_asn: 64513

interfaces:
  Loopback0:
    ip: 150.1.4.4/32
    description: mgmt_loopback
    enabled: true
  Management1:
    ip: 192.168.137.224/24
    vrf: MGMT
    description: oob
    enabled: true
  Ethernet1:
    ip: 155.0.0.5/31
    description: link_to_spine02
    enabled: true
  Ethernet2:
    mode: trunk
    description: link_to_k8s_nodes
    vlans: ['221']
    enabled: true
  Ethernet12:
    mode: trunk
    description: link_to_leaf01
    vlans: ['10', '221']
    enabled: true

vlans:
  10:
    ip: 155.0.0.7/31
    name: link_to_leaf01
    vrrp: false
  221:
    ip: 192.168.221.0/24
    name: K8S_SERVER_VLAN
    vrrp: true

bgp:
  - peer: 155.0.0.4
    asn: 64512
  - peer: 155.0.0.6
    asn: 64513
    next_hop_self: True
  - peer: 192.168.221.225
    asn: 64513
    peer_group: k8s_nodes
  - peer: 192.168.221.226
    asn: 64513
    peer_group: k8s_nodes
  - peer: 192.168.221.227
    asn: 64513
    peer_group: k8s_nodes

bgp_peer_groups:
  k8s_nodes:
    route_reflector_client: True
    next_hop_self: True
    description: k8s_nodes_ibgp
